version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: mailhog/mailhog:latest
    ports: ["1025", "8025"]
###< symfony/mailer ###
